Repository halo-dev/plugin-comment-widget, pull requests merged in 2023-07, with the labels that each got.

#42 feat: use autosize to automatically adjust the height of the edit box
  packages/comment-widget/package.json
  packages/comment-widget/src/components/Form.vue
  pnpm-lock.yaml
  src/main/resources/static/comment-widget.iife.js
Labels: kind/feature, release-note, approved, lgtm

#43 pref: make the comment component load asynchronously
  packages/widget/src/index.ts
  packages/widget/src/styles/style.css
  src/main/resources/static/comment-widget.iife.js
Labels: release-note, approved, lgtm, kind/improvement

#44 docs: update usage documentation of readme file
  README.md
Labels: release-note-none, kind/documentation, approved

#47 fix: content line break
  packages/comment-widget/src/components/CommentItem.vue
  packages/comment-widget/src/components/ReplyItem.vue
Labels: release-note-none, approved, lgtm

#46 chore: add halo app store release step
  .github/workflows/workflow.yaml
Labels: release-note-none, approved, lgtm, kind/improvement

#51 feat: add approved status in comment and reply list
  packages/comment-widget/src/components/CommentItem.vue
  packages/comment-widget/src/components/ReplyItem.vue
  src/main/resources/static/comment-widget.iife.js
  src/main/resources/static/style.css
Labels: release-note, approved, lgtm
