Repository halo-dev/plugin-comment-widget, pull requests merged in 2023-03, with the labels that each got.

#19 fix: getting user error
  packages/comment-widget/package.json
  packages/comment-widget/src/components/Comment.vue
  pnpm-lock.yaml
  src/main/resources/static/comment-widget.iife.js
  src/main/resources/static/style.css
Labels: kind/bug, release-note-none, approved, lgtm

#20 chore: release 1.3.0
  gradle.properties
  src/main/resources/plugin.yaml
Labels: release-note-none, approved, lgtm

#16 feat: add upvote supports
  packages/comment-widget/src/components/Comment.vue
  packages/comment-widget/src/components/CommentItem.vue
  packages/comment-widget/src/components/ReplyItem.vue
  packages/comment-widget/src/utils/api-client.ts
  src/main/resources/static/comment-widget.iife.js
  src/main/resources/static/style.css
Labels: kind/feature, release-note, approved, lgtm

#23 feat: add version parameter to static resources
  src/main/java/run/halo/comment/widget/DefaultCommentWidget.java
Labels: release-note, approved, lgtm, kind/improvement

#24 chore: release 1.4.0
  gradle.properties
  src/main/resources/plugin.yaml
Labels: release-note-none, approved, lgtm

#26 fix: emoji picker crash
  packages/comment-widget/package.json
  packages/comment-widget/src/components/Form.vue
  pnpm-lock.yaml
  src/main/resources/static/comment-widget.iife.js
  src/main/resources/static/style.css
Labels: kind/bug, release-note, approved, lgtm

#8 refactor: comment naming rule of dom id
  src/main/java/run/halo/comment/widget/DefaultCommentWidget.java
Labels: release-note, approved, lgtm

#25 feat: support logging in with encrypted password
  packages/comment-widget/package.json
  packages/comment-widget/src/components/LoginModal.vue
  packages/comment-widget/src/utils/api-client.ts
  pnpm-lock.yaml
Labels: kind/feature, release-note, approved, lgtm, kind/api-change

#27 chore: release 1.5.0
  gradle.properties
  src/main/resources/plugin.yaml
Labels: release-note-none, approved, lgtm
