Repository halo-dev/plugin-comment-widget, pull requests merged in 2024-03, with the labels that each got.

#83 fix: text color issue
  README.md
  packages/comment-widget/src/base-comment-item.ts
  packages/comment-widget/src/base-form.ts
  packages/comment-widget/src/comment-pagination.ts
  packages/comment-widget/src/comment-widget.ts
  packages/comment-widget/src/emoji-button.ts
  packages/comment-widget/src/styles/var.ts
  packages/comment-widget/var.css
Labels: kind/bug, release-note-none, approved, lgtm

#84 feat: improve styles of quote badge
  packages/comment-widget/src/reply-item.ts
Labels: release-note-none, approved, lgtm

#85 feat: add animation for emoji panel
  packages/comment-widget/src/emoji-button.ts
Labels: release-note-none, approved, lgtm, kind/improvement

#89 pref: Use base-info-color variable to unify non important prominent text
  README.md
  packages/comment-widget/src/base-comment-item-action.ts
  packages/comment-widget/src/base-comment-item.ts
  packages/comment-widget/src/emoji-button.ts
  packages/comment-widget/src/styles/var.ts
  packages/comment-widget/var.css
  packages/example/index.html
Labels: do-not-merge/release-note-label-needed, approved, lgtm

#99 feat: add shortcuts feature for form submission
  packages/comment-widget/src/base-form.ts
Labels: kind/feature, release-note, approved, lgtm

#98 Fix the issue of scrolling to the comment view after the initial loading of comments
  packages/comment-widget/src/comment-widget.ts
Labels: kind/bug, release-note, approved, lgtm

#103 fix: issue of the emoji picker being semi-transparent
  packages/comment-widget/src/emoji-button.ts
Labels: release-note, approved, lgtm

#104 feat: make the content editor focused when the reply form is opened
  packages/comment-widget/src/base-form.ts
  packages/comment-widget/src/reply-form.ts
Labels: kind/feature, release-note, approved, lgtm

#106 feat: fetch comments with related replies
  build.gradle
  packages/comment-widget/src/base-comment-item-action.ts
  packages/comment-widget/src/base-comment-item.ts
  packages/comment-widget/src/comment-item.ts
  packages/comment-widget/src/comment-replies.ts
  packages/comment-widget/src/comment-widget.ts
  packages/comment-widget/src/context/index.ts
  packages/comment-widget/src/reply-item.ts
  packages/example/index.html
  packages/widget/src/index.ts
  src/main/java/run/halo/comment/widget/DefaultCommentWidget.java
  src/main/resources/extensions/settings.yaml
  src/main/resources/plugin.yaml
Labels: release-note, approved, lgtm
