Repository halo-dev/plugin-comment-widget, pull requests merged in 2024-04, with the labels that each got.

#109 feat: add default size options
  build.gradle
  packages/comment-widget/package.json
  packages/comment-widget/src/comment-replies.ts
  packages/comment-widget/src/comment-widget.ts
  packages/comment-widget/src/context/index.ts
  packages/widget/src/index.ts
  pnpm-lock.yaml
  src/main/java/run/halo/comment/widget/DefaultCommentWidget.java
  src/main/resources/extensions/settings.yaml
Labels: release-note, approved, lgtm

#107 fix: form layout issue in mobile device
  packages/comment-widget/src/base-form.ts
Labels: kind/bug, release-note, approved, lgtm

#110 chore: change version to release 2.1.0
  packages/comment-widget/package.json
Labels: release-note-none, approved, lgtm

#111 feat: use gravatar source as comment's avatar
  packages/comment-widget/src/avatar/avatar-policy.ts
  packages/comment-widget/src/avatar/providers/avatar-provider.ts
  packages/comment-widget/src/avatar/providers/gravatar.ts
  packages/comment-widget/src/avatar/providers/index.ts
  packages/comment-widget/src/comment-item.ts
  packages/comment-widget/src/comment-widget.ts
  packages/comment-widget/src/context/index.ts
  packages/comment-widget/src/reply-item.ts
  packages/widget/src/index.ts
  src/main/java/run/halo/comment/widget/CommentWidgetPlugin.java
  src/main/java/run/halo/comment/widget/DefaultCommentWidget.java
  src/main/resources/extensions/settings.yaml
Labels: release-note, approved, lgtm

#113 feat: add aria-label attribute for emoji picker button
  packages/comment-widget/src/emoji-button.ts
Labels: release-note, approved, lgtm

#115 chore: refine plugin.yaml file
  src/main/resources/plugin.yaml
Labels: release-note-none, approved, lgtm
